### ISSUE TITLE
未混淆情况下是使用正常，混淆之后久无法使用视频通话功能。

### ISSUE THREAD

**Issue by liweijieok** [zhaoyang21cn/CallSDK_Android_Demo#70]
你好，我是使用 
```
 compile 'com.tencent.callsdk:callsdk:1.0.16'
```
 这个版本的sdk ，在未添加混淆之前，能够正常使用，添加了混淆之后，类ILVBLogin的iLiveLogin()方法就一直登陆失败，返回 

```
Key_Procedure|ILVB-iLiveLogin|login failed:6012|请求失败，请你稍后重试。
```
项目本身是有添加混淆代码的，本身有添加的混淆是：
```
-keep class com.tencent.**{*;}
-keep class com.tencent.**
-dontwarn com.tencent.**
-keep class tencent.**{*;}
-keep class tencent.**
-dontwarn tencent.**
-keep class qalsdk.**{*;}
-keep class qalsdk.**
-keep class com.tencent.ilivesdk.**
-keep class com.tencent.ilivesdk.**{*;}
-keep class com.tencent.callsdk.**
-keep class com.tencent.callsdk.**{*;}
-dontwarn qalsdk.**

```
服务器签名混淆与未混淆返回正常，现在问题是在ILVBLogin的iLiveLogin()方法中，混淆调用一直是返回6012错误，但是网络本身没有问题(未混淆可以正常使用)
请求如何解决呢？

**Comment by xkazer** [comment]
6012若排除网络问题，还可能是qal服务未正常启动，可以仔细看下初始化时日志，是否有so加载失败或class类找不到，排除下多架构问题，以及多dex问题

**Comment by liweijieok** [comment]
qal服务已经启动了。他的log如下：
```
12-06 16:50:05.432 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/System.out: [socket][/172.16.10.199:44784] connected
12-06 16:50:05.435 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/MSF.C.NetConnTag: open /59.37.116.121:14000 failed java.lang.RuntimeException: Stub!
                                                                                           at org.apache.http.e.a.<init>(ByteArrayBuffer.java:5)
                                                                                           at com.tencent.qalsdk.util.MsfSocketInputBuffer.init(MsfSocketInputBuffer.java:120)
                                                                                       	at com.tencent.qalsdk.uti costTime: 251 configTimeout: 8000
12-06 16:50:05.437 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/MSF.C.NetConnTag: try open Conn /101.226.68.116:80
12-06 16:50:05.438 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/System.out: [CDS]connect[/101.226.68.116:80] tm:8
12-06 16:50:05.479 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/System.out: [socket][/172.16.10.199:48997] connected
12-06 16:50:05.483 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/MSF.C.NetConnTag: open /101.226.68.116:80 failed java.lang.RuntimeException: Stub!
                                                                                           at org.apache.http.e.a.<init>(ByteArrayBuffer.java:5)
                                                                                           at com.tencent.qalsdk.util.MsfSocketInputBuffer.init(MsfSocketInputBuffer.java:120)
                                                                                       	at com.tencent.qalsdk.uti costTime: 43 configTimeout: 8000
12-06 16:50:05.494 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/MSF.C.NetConnTag: try open Conn /183.3.225.54:8080
12-06 16:50:05.496 17013-17085/com.qinyuanapp.genealogy:QALSERVICE I/System.out: [CDS]connect[/183.3.225.54:8080] tm:8
```

**Comment by liweijieok** [comment]
问题解决了，就是上面log的apache混淆的问题，混淆的时候把他也混淆了。加上
```
-keep class org.apache.**{*;}
-keep class org.apache.**
```
这个即可。
thanks。
